trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '14.x'
  - script: |
      npm install
    displayName: 'Install dependencies'
  - script: |
      npm run lint
    displayName: 'Lint code'
  - script: |
      npm run build
    displayName: 'Build project'
  - script: |
      npm test -- --coverage
    displayName: 'Run tests and collect coverage'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      failTaskOnFailedTests: true
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'